<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class BlogController extends Controller
{
    /**
     * Display a listing of the blogs
     */
    public function index()
    {
        try {
            $blogs = Blog::latest()->paginate(10);
            
            return response()->json([
                'status' => true,
                'message' => 'Blogs fetched successfully',
                'data' => $blogs
            ]);
        } catch (\Exception $e) {
            Log::error('Blog index error: ' . $e->getMessage());
            return response()->json([
                'status' => false,
                'message' => 'Error fetching blogs',
                'error' => $e->getMessage()
            ], 500);
        }
    }


    /**
 * Display simplified blog listing
 */
public function indexShow()
{
    try {
        $blogs = Blog::select('id', 'title', 'image', 'meta_data')
            ->latest()
            ->get()
            ->map(function ($blog) {
                return [
                    'id' => $blog->id,
                    'name' => $blog->title,
                    'slug' => $blog->slug,
                    'image' => $blog->image
                        ? asset('storage/' . $blog->image)
                        : null,
                    'meta_data' => $blog->meta_data,
                    'is_archived' => $blog->is_archived
                ];
            });

        return response()->json([
            'status' => true,
            'message' => 'Blog summary fetched successfully',
            'data' => $blogs
        ]);

    } catch (\Exception $e) {
        Log::error('Blog indexShow error: ' . $e->getMessage());

        return response()->json([
            'status' => false,
            'message' => 'Error fetching blog summary',
            'error' => $e->getMessage()
        ], 500);
    }
}

    /**
     * Store a newly created blog
     */
    public function store(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'title' => 'required|string|max:255',
                'short_description' => 'required|string',
                'long_description' => 'required|string',
                'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,webp|max:2048',
                'meta_data' => 'nullable|json',
                'is_archived' => 'nullable|boolean',
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'status' => false,
                    'errors' => $validator->errors()
                ], 422);
            }

            $data = [
                'title' => $request->title,
                'short_description' => $request->short_description,
                'long_description' => $request->long_description,
                'meta_data' => $request->meta_data,
                'is_archived' => $request->boolean('is_archived', false),
            ];

            // Handle Image Upload
            if ($request->hasFile('image') && $request->file('image')->isValid()) {
                $imagePath = $request->file('image')->store('blogs', 'public');
                $data['image'] = $imagePath;
            }

            // Create blog - slug will be auto-generated by the model's boot method
            $blog = Blog::create($data);

            $this->logActivity("Created blog: {$blog->title}");

            return response()->json([
                'status' => true,
                'message' => 'Blog created successfully',
                'data' => $blog->fresh() // Get fresh instance with slug
            ], 201);
            
        } catch (\Exception $e) {
            Log::error('Blog store error: ' . $e->getMessage());
            Log::error('Stack trace: ' . $e->getTraceAsString());
            
            return response()->json([
                'status' => false,
                'message' => 'Error creating blog',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Update the specified blog
     */
    public function update(Request $request, $id)
    {
        try {
            $blog = Blog::find($id);

            if (!$blog) {
                return response()->json([
                    'status' => false,
                    'message' => 'Blog not found'
                ], 404);
            }

            $validator = Validator::make($request->all(), [
                'title' => 'sometimes|required|string|max:255',
                'short_description' => 'sometimes|required|string',
                'long_description' => 'sometimes|required|string',
                'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,webp|max:2048',
                'meta_data' => 'nullable|json',
                'is_archived' => 'nullable|boolean',
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'status' => false,
                    'errors' => $validator->errors()
                ], 422);
            }

            $data = [
                'title' => $request->title ?? $blog->title,
                'short_description' => $request->short_description ?? $blog->short_description,
                'long_description' => $request->long_description ?? $blog->long_description,
                'meta_data' => $request->meta_data ?? $blog->meta_data,
                'is_archived' => $request->has('is_archived') ? $request->boolean('is_archived') : $blog->is_archived,
            ];

            // Handle Image Update
            if ($request->hasFile('image') && $request->file('image')->isValid()) {
                // Delete old image if exists
                if ($blog->image && \Storage::disk('public')->exists($blog->image)) {
                    \Storage::disk('public')->delete($blog->image);
                }
                
                $imagePath = $request->file('image')->store('blogs', 'public');
                $data['image'] = $imagePath;
            }

            // Update slug if title changed
            if (isset($data['title']) && $data['title'] !== $blog->title) {
                $data['slug'] = Str::slug($data['title']) . '-' . $blog->id;
            }

            $blog->update($data);

            $this->logActivity("Updated blog: {$blog->title}");

            return response()->json([
                'status' => true,
                'message' => 'Blog updated successfully',
                'data' => $blog
            ]);
            
        } catch (\Exception $e) {
            Log::error('Blog update error: ' . $e->getMessage());
            Log::error('Stack trace: ' . $e->getTraceAsString());
            
            return response()->json([
                'status' => false,
                'message' => 'Error updating blog',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified blog
     */
    public function destroy($id)
    {
        try {
            $blog = Blog::find($id);

            if (!$blog) {
                return response()->json([
                    'status' => false,
                    'message' => 'Blog not found'
                ], 404);
            }

            // Delete image if exists
            if ($blog->image && \Storage::disk('public')->exists($blog->image)) {
                \Storage::disk('public')->delete($blog->image);
            }

            $blog->delete();

            $this->logActivity("Deleted blog: {$blog->title}");

            return response()->json([
                'status' => true,
                'message' => 'Blog deleted successfully'
            ]);
            
        } catch (\Exception $e) {
            Log::error('Blog delete error: ' . $e->getMessage());
            
            return response()->json([
                'status' => false,
                'message' => 'Error deleting blog',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
